Matricula/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from usuarios import views as usuarios_views
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registro/(alumno|profesor)/$', usuarios_views.registro, name='registro'),
    url(r'^login/$', auth_views.login, {'template_name': 'usuarios/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': reverse_lazy('gestion:index')}, name='logout'),
    url(r'^', include('gestion.urls', namespace='gestion'), name='gestion'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gestion/urls.py
from django.conf.urls import url
from gestion.views import *

urlpatterns = [
	url(r'^$', Index.as_view(), name='index'),
	url(r'^expediente/$', ListaCursosAlumno.as_view(), name='expediente'),
	url(r'^expediente/(?P<curso>\d+)/$', ListaAsignaturasAlumno.as_view(), name='curso'),
	url(r'^expediente/(?P<curso>\d+)/(?P<asig>\d+)/$', DetalleNotas.as_view(), name='asignatura'),
	url(r'^nuevamatricula/$', ListaCursosAlumnoMatricula.as_view(), name='cursosmatricula'),
	url(r'^nuevamatricula/(?P<curso>\d+)/$', NuevaMatricula.as_view(), name='matricula'),
	url(r'^verificarprofesor/$', VerificarProfesor.as_view(), name='verificarprofesor'),
	url(r'^verificarprofesor/v/(?P<prof>\d+)/$', VerificarProfesorA.as_view(verificar=True), name='verificarp'),
	url(r'^verificarprofesor/e/(?P<prof>\d+)/$', VerificarProfesorA.as_view(verificar=False), name='eliminarp'),
	url(r'^gestioncursos/$', ListaGestionCursos.as_view(), name='gestioncursos'),
	url(r'^gestionasignaturas/$', ListaGestionAsignaturas.as_view(), name='gestionasignaturas'),
	url(r'^gestioncarreras/$', ListaGestionCarreras.as_view(), name='gestioncarreras'),
	url(r'^gestioncursos/nuevo/$', NuevoCurso.as_view(), name='nuevocurso'),
	url(r'^gestionasignaturas/nuevo/$', NuevaAsignatura.as_view(), name='nuevaasignatura'),
	url(r'^gestioncarreras/nuevo/$', NuevaCarrera.as_view(), name='nuevacarrera'),
	url(r'^calificar/$', ListaAsigProf.as_view(calificar=True), name='asignaturascalificar'),
	url(r'^calificar/(?P<asig>\d+)/$', ListaAlum.as_view(actual=True), name='alumnoscalificar'),
	url(r'^calificar/(?P<asig>\d+)/(?P<alum>\d+)/$', Calificar.as_view(), name='calificar'),
	url(r'^consultar/$', ListaAsigProf.as_view(), name='asignaturasconsultar'),
	url(r'^consultar/(?P<asig>\d+)/$', ListaCursosProf.as_view(), name='cursosconsultar'),
	url(r'^consultar/(?P<asig>\d+)/(?P<curso>\d+)/$', ListaAlum.as_view(), name='alumnosconsultar'),
	url(r'^consultar/(?P<asig>\d+)/(?P<curso>\d+)/(?P<alum>\d+)/$', DetalleNotas.as_view(profesor=True), name='consultar'),
	url(r'^instrucciones/$', Instrucciones.as_view(), name='instrucciones'),
]

gestion/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime, date
from usuarios.models import Usuario, Carrera, Asignatura
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class Curso(models.Model):
	YEAR_OPCIONES = []
	for r in range(datetime.now().year-5, datetime.now().year+5):
		YEAR_OPCIONES.append((r,str(r)+'/'+str(r+1)))
	year = models.IntegerField(choices=YEAR_OPCIONES, unique=True)
	inicioMatricula = models.DateField('Inicio matriculacion')
	finMatricula = models.DateField('Fin matriculacion')
	def getCadena(self):
		return str(self.year)+'/'+str(self.year+1)
	def abierto(self):
		if (date.today() >= self.inicioMatricula and date.today() <= self.finMatricula):
			return True
		else:
			return False
	def __str__(self):
		return self.getCadena()

class MatriculaAsignatura(models.Model):
	nota1 = models.DecimalField(validators = [MinValueValidator(0), MaxValueValidator(10)], max_digits=4, decimal_places=2, blank=True, null=True)
	noPresentado1 = models.BooleanField(default = False)
	matriculaHonor1 = models.BooleanField(default = False)
	nota2 = models.DecimalField(validators = [MinValueValidator(0), MaxValueValidator(10)], max_digits=4, decimal_places=2, blank=True, null=True)
	noPresentado2 = models.BooleanField(default = False)
	matriculaHonor2 = models.BooleanField(default = False)
	alumno = models.ForeignKey(Usuario)
	asignatura = models.ForeignKey(Asignatura)
	curso = models.ForeignKey(Curso)
	def __str__(self):
		return self.alumno.__str__() + " - " + self.asignatura.__str__() + " - " + self.curso.__str__()

gestion/forms.py
from django.forms import ModelForm, Form, ModelMultipleChoiceField
from gestion.models import *
from usuarios.models import *
from django.contrib.admin import widgets

class MatriculaForm(Form):
	def __init__(self,*args,**kwargs):
		obj1 = kwargs.pop('obj1')
		obj2 = kwargs.pop('obj2')
		super(MatriculaForm,self).__init__(*args,**kwargs)
		self.fields['cuatrimestre1']=ModelMultipleChoiceField(obj1)
		self.fields['cuatrimestre2']=ModelMultipleChoiceField(obj2)

	class Meta:
		fields = ('cuatrimestre1','cuatrimestre2')

	def save(self, u, c):
		asignaturas=self.cleaned_data["cuatrimestre1"]
		for asig in asignaturas:
			mat=MatriculaAsignatura(alumno=u, curso=c, asignatura=asig)
			mat.save()
		asignaturas=self.cleaned_data["cuatrimestre2"]
		for asig in asignaturas:
			mat=MatriculaAsignatura(alumno=u, curso=c, asignatura=asig)
			mat.save()

class CursoForm(ModelForm):
	class Meta:
		model = Curso
		fields = ['year', 'inicioMatricula', 'finMatricula']

class AsignaturaForm(ModelForm):
	class Meta:
		model = Asignatura
		fields = ['nombre', 'curso', 'cuatrimestre', 'carrera']

class CarreraForm(ModelForm):
	class Meta:
		model = Carrera
		fields = ['nombre',]

class CalificarForm(ModelForm):
	class Meta:
		model = MatriculaAsignatura
		fields = ['nota1','matriculaHonor1','noPresentado1','nota2','matriculaHonor2','noPresentado2']

gestion/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, FormView
from gestion.models import *
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime, date
from gestion.forms import *
from usuarios.models import Asignatura
from django.conf import settings
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login

class RequiereLogin(LoginRequiredMixin):
	login_url = '/login/'

class EsAlumno(UserPassesTestMixin):
	def handle_no_permission(self):
		if self.request.user.is_authenticated:
			return render(self.request, 'base.html', {'sinpermiso':True})
		return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

	def test_func(self):
		return (not self.request.user.is_staff and not self.request.user.is_superuser)

class EsProfesor(UserPassesTestMixin):
	def test_func(self):
		return (self.request.user.is_staff and not self.request.user.is_superuser)

class EsAdmin(UserPassesTestMixin):
	def test_func(self):
		return self.request.user.is_superuser

class Index(View):
	template_name = 'gestion/index.html'
	def get(self, request):
		return render(request, self.template_name)

class Instrucciones(View):
	template_name = 'gestion/instrucciones.html'
	def get(self, request):
		return render(request, self.template_name)

class ListaCursosAlumno(RequiereLogin, EsAlumno, ListView):
	model = Curso
	template_name = 'gestion/listacursosexp.html'
	context_object_name = 'lista_de_cursos'
	def get_queryset(self):
		misMatriculas = MatriculaAsignatura.objects.filter(alumno=self.request.user)
		misCursos = [p.curso for p in misMatriculas] #hay elementos duplicados ya que se anade a la lista un curso por cada asignatura
		misCursos = list(set(misCursos)) #se eliminan los elementos duplicados con list y set
		return misCursos

class ListaAsignaturasAlumno(RequiereLogin, EsAlumno, ListView):
	model = MatriculaAsignatura
	template_name = 'gestion/listaasignaturas.html'
	context_object_name = 'lista_de_matriculas'
	def get_queryset(self):
		misMatriculas = MatriculaAsignatura.objects.filter(alumno=self.request.user, curso=self.kwargs['curso'])
		return misMatriculas

class DetalleNotas(RequiereLogin, View):
	template_name = 'gestion/detalle.html'
	profesor = False
	def get(self, request, *args, **kwargs):
		asig = self.kwargs['asig']
		cur = self.kwargs['curso']
		if self.profesor:
			alum = self.kwargs['alum']
		else:
			alum = request.user.id
		matricula = MatriculaAsignatura.objects.get(alumno=alum, asignatura=asig, curso=cur)
		profesores = Usuario.objects.filter(profesorSinVerificar=False, imparte__in=[asig])
		return render(request, self.template_name, {'matricula':matricula, 'profesores':profesores, 'profesor':self.profesor})

class ListaCursosAlumnoMatricula(RequiereLogin, EsAlumno, ListView):
	model = Curso
	template_name = 'gestion/listacursosmat.html'
	context_object_name = 'lista_de_cursos'
	def get_queryset(self):
		misCursos = Curso.objects.filter(year__gte=(datetime.now().year-1))
		return misCursos

class NuevaMatricula(RequiereLogin, EsAlumno, View):
	template_name = 'gestion/nuevamatricula.html'
	form_class = MatriculaForm
	def get(self, request, *args, **kwargs):
		misMatriculas = MatriculaAsignatura.objects.filter(alumno=self.request.user)
		misCursos = [p.curso for p in misMatriculas] #hay elementos duplicados ya que se anade a la lista un curso por cada asignatura
		misCursos = list(set(misCursos)) #se eliminan los elementos duplicados con list y set
		curso = Curso.objects.get(id=self.kwargs['curso'])
		if curso in misCursos:
			context = {'error':1} #Ya estas matriculado en este curso
		elif (date.today() < curso.inicioMatricula or date.today() > curso.finMatricula):
			context = {'error':2} #El plazo de matricula esta cerrado
		else:
			asignaturas1 = self.lista(user=request.user, cuatr=1)
			asignaturas2 = self.lista(user=request.user, cuatr=2)
			form = self.form_class(obj1=asignaturas1, obj2=asignaturas2) #Se pasan al formulario las listas de asignaturas que debe mostrar
			context = {'form':form, 'curso':curso}
		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		asignaturas1 = self.lista(user=request.user, cuatr=1)
		asignaturas2 = self.lista(user=request.user, cuatr=2)
		form = self.form_class(request.POST, obj1=asignaturas1, obj2=asignaturas2)
		curso = Curso.objects.get(id=self.kwargs['curso'])
		if form.is_valid():
			form.save(u=request.user, c=curso)
			return redirect('/')
		else:
			context = {'form':form, 'curso':curso}
			return render(request, self.template_name, context)

	def lista(self, user, cuatr):
		asignaturas = Asignatura.objects.filter(cuatrimestre=cuatr, carrera=user.carrera)
		cursadas = MatriculaAsignatura.objects.filter(alumno=user)
		for asig in asignaturas:
			for curs in cursadas:
				if (asig == curs.asignatura and (curs.nota1 >= 5 or curs.nota2 >= 5)):
					asignaturas = asignaturas.exclude(id=asig.id) #Se excluyen de la lista las asignaturas aprobadas
		return asignaturas

class VerificarProfesor(RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/verificarprofesor.html'
	model = Usuario
	context_object_name = 'lista_de_profesores'
	def get_queryset(self):
		profesores = Usuario.objects.filter(profesorSinVerificar=True)
		return profesores

class VerificarProfesorA(RequiereLogin, EsAdmin, View):
	verificar = True;
	def get(self, request, *args, **kwargs):
		profid = self.kwargs['prof']
		prof = Usuario.objects.get(id=profid)
		if self.verificar:
			prof.profesorSinVerificar = False
			prof.is_staff = True
			prof.save()
		else:
			prof.delete()
		return redirect('/verificarprofesor/')

class ListaGestionCursos (RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/gestioncursos.html'
	model = Curso
	context_object_name = 'lista_de_cursos'
	def get_queryset(self):
		cursos = Curso.objects.all()
		return cursos

class ListaGestionAsignaturas (RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/gestionasignaturas.html'
	model = Asignatura
	context_object_name = 'lista_de_asignaturas'
	def get_queryset(self):
		asignaturas = Asignatura.objects.all()
		return asignaturas

class ListaGestionCarreras (RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/gestioncarreras.html'
	model = Carrera
	context_object_name = 'lista_de_carreras'
	def get_queryset(self):
		carreras = Carrera.objects.all()
		return carreras

class NuevoCurso (RequiereLogin, EsAdmin, FormView):
	template_name = 'gestion/nuevo.html'
	form_class = CursoForm
	success_url = '/gestioncursos/'
	def form_valid(self, form):
		form.save()
		return super(NuevoCurso, self).form_valid(form)

class NuevaAsignatura (RequiereLogin, EsAdmin, FormView):
	template_name = 'gestion/nuevo.html'
	form_class = AsignaturaForm
	success_url = '/gestionasignaturas/'
	def form_valid(self, form):
		form.save()
		return super(NuevaAsignatura, self).form_valid(form)

class NuevaCarrera (RequiereLogin, EsAdmin, FormView):
	template_name = 'gestion/nuevo.html'
	form_class = CarreraForm
	success_url = '/gestioncarreras/'
	def form_valid(self, form):
		form.save()
		return super(NuevaCarrera, self).form_valid(form)

class ListaAsigProf (RequiereLogin, EsProfesor, View):
	template_name = 'gestion/listaasignaturasprof.html'
	context_object_name = 'lista_de_asignaturas'
	calificar=False
	def get(self, request):
		carreras = request.user.imparte.all()
		return render(request, self.template_name, {self.context_object_name:carreras, 'calificar':self.calificar})

def cursoActual():
	if (date.today().month < settings.FIN_CURSO_MES):
		year=date.today().year-1
	elif (date.today().moth == settings.FIN_CURSO_MES and date.today().day < settings.FIN_CURSO_DIA):
		year=date.today().year-1
	else:
		year=date.today().year
	curso=Curso.objects.get(year=year)
	return curso;

class ListaAlum (RequiereLogin, EsProfesor, View):
	template_name = 'gestion/listaalumnosprof.html'
	context_object_name = 'lista_de_matriculas'
	actual = False
	def get(self, request, *args, **kwargs):
		if self.actual:
			curso = cursoActual()
		else:
			curso = Curso.objects.get(id=self.kwargs['curso'])
		matriculas = MatriculaAsignatura.objects.filter(curso=curso, asignatura=self.kwargs['asig'])
		context = {self.context_object_name:matriculas,}
		if self.actual: context['calificar']=True
		return render(request, self.template_name, context)

class ListaCursosProf (RequiereLogin, EsProfesor, View):
	template_name = 'gestion/listacursosprof.html'
	context_object_name = 'lista_de_cursos'
	def get(self, request, *args, **kwargs):
		cursos = Curso.objects.filter(year__lte=cursoActual().year)
		return render(request, self.template_name, {self.context_object_name:cursos,})

class Calificar(RequiereLogin, EsProfesor, View):
	template_name = 'gestion/calificar.html'
	form_class = CalificarForm
	def get(self, request, *args, **kwargs):
		matricula=MatriculaAsignatura.objects.get(curso=cursoActual(), alumno=self.kwargs['alum'], asignatura=self.kwargs['asig'])
		form = self.form_class(instance=matricula)
		context = {'form':form, 'matricula':matricula}
		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		matricula=MatriculaAsignatura.objects.get(curso=cursoActual(), alumno=self.kwargs['alum'], asignatura=self.kwargs['asig'])
		if form.is_valid():
			matriculaf = form.save(commit=False)
			matricula.nota1=matriculaf.nota1
			matricula.nota2=matriculaf.nota2
			matricula.matriculaHonor1=matriculaf.matriculaHonor1
			matricula.matriculaHonor2=matriculaf.matriculaHonor2
			matricula.noPresentado1=matriculaf.noPresentado1
			matricula.noPresentado2=matriculaf.noPresentado2
			matricula.save()
			return redirect('/calificar/'+self.kwargs['asig'])
		else:
			context = {'form':form, 'matricula':matricula}

gestion/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Gestión de Matrícula{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- LIBRERIAS BOOTSTRAP -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="http://getbootstrap.com/examples/sticky-footer/sticky-footer.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% block head %}{% endblock %}

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px;}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    footer {
      background-color: #555;
      color: white;
      padding: 15px;
      position: absolute;
	  bottom: 0;
	  width: 100%;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'gestion:index' %}">GeMa</span></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="{% block indexa %}{% endblock %}"><a href="{% url 'gestion:index' %}">Inicio</a></li>
        {% if request.user.is_superuser %}
        <li class="{% block verificara %}{% endblock %}"><a href="{% url 'gestion:verificarprofesor' %}">Verificar Profesores</a></li>
        <li class="{% block cursosa %}{% endblock %}"><a href="{% url 'gestion:gestioncursos' %}">Cursos</a></li>
        <li class="{% block carrerasa %}{% endblock %}"><a href="{% url 'gestion:gestioncarreras' %}">Carreras</a></li>
        <li class="{% block asignaturasa %}{% endblock %}"><a href="{% url 'gestion:gestionasignaturas' %}">Asignaturas</a></li>
        {% elif request.user.is_staff %}
        <li class="{% block calificara %}{% endblock %}"><a href="{% url 'gestion:asignaturascalificar' %}">Calificar</a></li>
        <li class="{% block todosa %}{% endblock %}"><a href="{% url 'gestion:asignaturasconsultar' %}">Todos los Cursos</a></li>
        {% elif request.user.is_authenticated and not request.user.profesorSinVerificar %}
        <li class="{% block matricularmea %}{% endblock %}"><a href="{% url 'gestion:cursosmatricula' %}">Matricularme</a></li>
        <li class="{% block expedientea %}{% endblock %}"><a href="{% url 'gestion:expediente' %}">Consultar Expediente</a></li>
        {% endif %}
        <li class="{% block instruccionesa %}{% endblock %}"><a href="{% url 'gestion:instrucciones' %}">Instrucciones</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <li><a href="{% url 'registro' 'alumno' %}"><span class="glyphicon glyphicon-new-window"></span> Registro</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2">
      <br><br>
      <div style="height:120px;"><p><a href="http://www.uco.es/"><img src="{% static 'gestion/uco.gif' %}" width=260 alt="UCO" onmouseover="this.width=280;" onmouseout="this.width=260;"/><p></a></p></div>
      <div style="height:120px;"><p><a href="http://moodle.uco.es/"><img src="{% static 'gestion/moodle.png' %}" width=260 alt="Moodle" onmouseover="this.width=280;" onmouseout="this.width=260;"/></a></p></div>
      <div style="height:120px;"><p><a href="https://www.djangoproject.com/"><img src="{% static 'gestion/django.png' %}" width=260 alt="UCO" onmouseover="this.width=280;" onmouseout="this.width=260;"/><p></a></p></div>
      <div style="height:120px;"><p><a href="http://getbootstrap.com/"><img src="{% static 'gestion/bootstrap.png' %}" width=260 alt="UCO" onmouseover="this.width=280;" onmouseout="this.width=260;"/><p></a></p></div>
    </div>
    <div class="col-sm-8 text-left">
    {% if sinpermiso %}
      <br><br><br>
      <div class="alert alert-danger">
        <strong>Acceso Denegado!</strong> No tienes permiso para acceder a esta página.
      </div>
    {% else %}
      <h1>{% block titulo %}{% endblock %}</h1>
	    <hr width=100% align="center"> 
      {% block content %}{% endblock %}
    {% endif %}
    </div>
    <div class="col-sm-2">
      <br><br>
      {% if request.user.is_authenticated %}
      <div class="well">
        <p>Bienvenido {{ request.user.username }}</p>
        <p>
        {% if request.user.is_superuser %}
        (Administrador)
        {% elif request.user.is_staff or request.user.profesorSinVerificar %}
        (Profesor)
        {% else %}
        (Alumno de {{ request.user.carrera.nombre }})
        {% endif %}
      </div>
      {% if not request.user.is_superuser %}
      <div class="well">
        <p>{{ request.user.first_name }} {{ request.user.last_name }}</p>
      </div>
      {% endif %}
        {% if request.user.profesorSinVerificar %}
          <div class="alert alert-danger">
            <strong>Atención!</strong> Tu cuenta debe ser verificada por un administrador. No podrás realizar gestiones hasta entonces.
          </div>
        {% endif %}
      {% else %}
      <div class="well">
        <p>Bienvenido Invitado</p>
      </div>
      <div class="well">
        <p>Inicia sesión o registrate para comenzar</p>
      </div>
      {% endif %}
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Realizado por: Álvaro Herrero Pérez</p>
</footer>

</body>
</html>