Matricula/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from usuarios import views as usuarios_views
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registro/(alumno|profesor)/$', usuarios_views.registro, name='registro'),
    url(r'^login/$', auth_views.login, {'template_name': 'usuarios/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': reverse_lazy('gestion:index')}, name='logout'),
    url(r'^', include('gestion.urls', namespace='gestion'), name='gestion'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gestion/urls.py
from django.conf.urls import url
from gestion.views import *

urlpatterns = [
	url(r'^$', Index.as_view(), name='index'),
	url(r'^expediente/$', ListaCursosAlumno.as_view(), name='expediente'),
	url(r'^expediente/(?P<curso>\d+)/$', ListaAsignaturasAlumno.as_view(), name='curso'),
	url(r'^expediente/(?P<curso>\d+)/(?P<asig>\d+)/$', DetalleNotas.as_view(), name='asignatura'),
	url(r'^nuevamatricula/$', ListaCursosAlumnoMatricula.as_view(), name='cursosmatricula'),
	url(r'^nuevamatricula/(?P<curso>\d+)/$', NuevaMatricula.as_view(), name='matricula'),
	url(r'^verificarprofesor/$', VerificarProfesor.as_view(), name='verificarprofesor'),
	url(r'^verificarprofesor/v/(?P<prof>\d+)/$', VerificarProfesorA.as_view(verificar=True), name='verificarp'),
	url(r'^verificarprofesor/e/(?P<prof>\d+)/$', VerificarProfesorA.as_view(verificar=False), name='eliminarp'),
	url(r'^gestioncursos/$', ListaGestionCursos.as_view(), name='gestioncursos'),
	url(r'^gestionasignaturas/$', ListaGestionAsignaturas.as_view(), name='gestionasignaturas'),
	url(r'^gestioncarreras/$', ListaGestionCarreras.as_view(), name='gestioncarreras'),
	url(r'^gestioncursos/nuevo/$', NuevoCurso.as_view(), name='nuevocurso'),
	url(r'^gestionasignaturas/nuevo/$', NuevaAsignatura.as_view(), name='nuevaasignatura'),
	url(r'^gestioncarreras/nuevo/$', NuevaCarrera.as_view(), name='nuevacarrera'),
	url(r'^calificar/$', ListaAsigProf.as_view(calificar=True), name='asignaturascalificar'),
	url(r'^calificar/(?P<asig>\d+)/$', ListaAlum.as_view(actual=True), name='alumnoscalificar'),
	url(r'^calificar/(?P<asig>\d+)/(?P<alum>\d+)/$', Calificar.as_view(), name='calificar'),
	url(r'^consultar/$', ListaAsigProf.as_view(), name='asignaturasconsultar'),
	url(r'^consultar/(?P<asig>\d+)/$', ListaCursosProf.as_view(), name='cursosconsultar'),
	url(r'^consultar/(?P<asig>\d+)/(?P<curso>\d+)/$', ListaAlum.as_view(), name='alumnosconsultar'),
	url(r'^consultar/(?P<asig>\d+)/(?P<curso>\d+)/(?P<alum>\d+)/$', DetalleNotas.as_view(profesor=True), name='consultar'),
	url(r'^instrucciones/$', Instrucciones.as_view(), name='instrucciones'),
]

gestion/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime, date
from usuarios.models import Usuario, Carrera, Asignatura
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class Curso(models.Model):
	YEAR_OPCIONES = []
	for r in range(datetime.now().year-5, datetime.now().year+5):
		YEAR_OPCIONES.append((r,str(r)+'/'+str(r+1)))
	year = models.IntegerField(choices=YEAR_OPCIONES, unique=True)
	inicioMatricula = models.DateField('Inicio matriculacion')
	finMatricula = models.DateField('Fin matriculacion')
	def getCadena(self):
		return str(self.year)+'/'+str(self.year+1)
	def abierto(self):
		if (date.today() >= self.inicioMatricula and date.today() <= self.finMatricula):
			return True
		else:
			return False
	def __str__(self):
		return self.getCadena()

class MatriculaAsignatura(models.Model):
	nota1 = models.DecimalField(validators = [MinValueValidator(0), MaxValueValidator(10)], max_digits=4, decimal_places=2, blank=True, null=True)
	noPresentado1 = models.BooleanField(default = False)
	matriculaHonor1 = models.BooleanField(default = False)
	nota2 = models.DecimalField(validators = [MinValueValidator(0), MaxValueValidator(10)], max_digits=4, decimal_places=2, blank=True, null=True)
	noPresentado2 = models.BooleanField(default = False)
	matriculaHonor2 = models.BooleanField(default = False)
	alumno = models.ForeignKey(Usuario)
	asignatura = models.ForeignKey(Asignatura)
	curso = models.ForeignKey(Curso)
	def __str__(self):
		return self.alumno.__str__() + " - " + self.asignatura.__str__() + " - " + self.curso.__str__()

gestion/forms.py
from django.forms import ModelForm, Form, ModelMultipleChoiceField
from gestion.models import *
from usuarios.models import *
from django.contrib.admin import widgets

class MatriculaForm(Form):
	def __init__(self,*args,**kwargs):
		obj1 = kwargs.pop('obj1')
		obj2 = kwargs.pop('obj2')
		super(MatriculaForm,self).__init__(*args,**kwargs)
		self.fields['cuatrimestre1']=ModelMultipleChoiceField(obj1)
		self.fields['cuatrimestre2']=ModelMultipleChoiceField(obj2)

	class Meta:
		fields = ('cuatrimestre1','cuatrimestre2')

	def save(self, u, c):
		asignaturas=self.cleaned_data["cuatrimestre1"]
		for asig in asignaturas:
			mat=MatriculaAsignatura(alumno=u, curso=c, asignatura=asig)
			mat.save()
		asignaturas=self.cleaned_data["cuatrimestre2"]
		for asig in asignaturas:
			mat=MatriculaAsignatura(alumno=u, curso=c, asignatura=asig)
			mat.save()

class CursoForm(ModelForm):
	class Meta:
		model = Curso
		fields = ['year', 'inicioMatricula', 'finMatricula']

class AsignaturaForm(ModelForm):
	class Meta:
		model = Asignatura
		fields = ['nombre', 'curso', 'cuatrimestre', 'carrera']

class CarreraForm(ModelForm):
	class Meta:
		model = Carrera
		fields = ['nombre',]

class CalificarForm(ModelForm):
	class Meta:
		model = MatriculaAsignatura
		fields = ['nota1','matriculaHonor1','noPresentado1','nota2','matriculaHonor2','noPresentado2']

gestion/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, FormView
from gestion.models import *
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime, date
from gestion.forms import *
from usuarios.models import Asignatura
from django.conf import settings
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login

class RequiereLogin(LoginRequiredMixin):
	login_url = '/login/'

class EsAlumno(UserPassesTestMixin):
	def handle_no_permission(self):
		if self.request.user.is_authenticated:
			return render(self.request, 'base.html', {'sinpermiso':True})
		return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

	def test_func(self):
		return (not self.request.user.is_staff and not self.request.user.is_superuser)

class EsProfesor(UserPassesTestMixin):
	def test_func(self):
		return (self.request.user.is_staff and not self.request.user.is_superuser)

class EsAdmin(UserPassesTestMixin):
	def test_func(self):
		return self.request.user.is_superuser

class Index(View):
	template_name = 'gestion/index.html'
	def get(self, request):
		return render(request, self.template_name)

class Instrucciones(View):
	template_name = 'gestion/instrucciones.html'
	def get(self, request):
		return render(request, self.template_name)

class ListaCursosAlumno(RequiereLogin, EsAlumno, ListView):
	model = Curso
	template_name = 'gestion/listacursosexp.html'
	context_object_name = 'lista_de_cursos'
	def get_queryset(self):
		misMatriculas = MatriculaAsignatura.objects.filter(alumno=self.request.user)
		misCursos = [p.curso for p in misMatriculas] #hay elementos duplicados ya que se anade a la lista un curso por cada asignatura
		misCursos = list(set(misCursos)) #se eliminan los elementos duplicados con list y set
		return misCursos

class ListaAsignaturasAlumno(RequiereLogin, EsAlumno, ListView):
	model = MatriculaAsignatura
	template_name = 'gestion/listaasignaturas.html'
	context_object_name = 'lista_de_matriculas'
	def get_queryset(self):
		misMatriculas = MatriculaAsignatura.objects.filter(alumno=self.request.user, curso=self.kwargs['curso'])
		return misMatriculas

class DetalleNotas(RequiereLogin, View):
	template_name = 'gestion/detalle.html'
	profesor = False
	def get(self, request, *args, **kwargs):
		asig = self.kwargs['asig']
		cur = self.kwargs['curso']
		if self.profesor:
			alum = self.kwargs['alum']
		else:
			alum = request.user.id
		matricula = MatriculaAsignatura.objects.get(alumno=alum, asignatura=asig, curso=cur)
		profesores = Usuario.objects.filter(profesorSinVerificar=False, imparte__in=[asig])
		return render(request, self.template_name, {'matricula':matricula, 'profesores':profesores, 'profesor':self.profesor})

class ListaCursosAlumnoMatricula(RequiereLogin, EsAlumno, ListView):
	model = Curso
	template_name = 'gestion/listacursosmat.html'
	context_object_name = 'lista_de_cursos'
	def get_queryset(self):
		misCursos = Curso.objects.filter(year__gte=(datetime.now().year-1))
		return misCursos

class NuevaMatricula(RequiereLogin, EsAlumno, View):
	template_name = 'gestion/nuevamatricula.html'
	form_class = MatriculaForm
	def get(self, request, *args, **kwargs):
		misMatriculas = MatriculaAsignatura.objects.filter(alumno=self.request.user)
		misCursos = [p.curso for p in misMatriculas] #hay elementos duplicados ya que se anade a la lista un curso por cada asignatura
		misCursos = list(set(misCursos)) #se eliminan los elementos duplicados con list y set
		curso = Curso.objects.get(id=self.kwargs['curso'])
		if curso in misCursos:
			context = {'error':1} #Ya estas matriculado en este curso
		elif (date.today() < curso.inicioMatricula or date.today() > curso.finMatricula):
			context = {'error':2} #El plazo de matricula esta cerrado
		else:
			asignaturas1 = self.lista(user=request.user, cuatr=1)
			asignaturas2 = self.lista(user=request.user, cuatr=2)
			form = self.form_class(obj1=asignaturas1, obj2=asignaturas2) #Se pasan al formulario las listas de asignaturas que debe mostrar
			context = {'form':form, 'curso':curso}
		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		asignaturas1 = self.lista(user=request.user, cuatr=1)
		asignaturas2 = self.lista(user=request.user, cuatr=2)
		form = self.form_class(request.POST, obj1=asignaturas1, obj2=asignaturas2)
		curso = Curso.objects.get(id=self.kwargs['curso'])
		if form.is_valid():
			form.save(u=request.user, c=curso)
			return redirect('/')
		else:
			context = {'form':form, 'curso':curso}
			return render(request, self.template_name, context)

	def lista(self, user, cuatr):
		asignaturas = Asignatura.objects.filter(cuatrimestre=cuatr, carrera=user.carrera)
		cursadas = MatriculaAsignatura.objects.filter(alumno=user)
		for asig in asignaturas:
			for curs in cursadas:
				if (asig == curs.asignatura and (curs.nota1 >= 5 or curs.nota2 >= 5)):
					asignaturas = asignaturas.exclude(id=asig.id) #Se excluyen de la lista las asignaturas aprobadas
		return asignaturas

class VerificarProfesor(RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/verificarprofesor.html'
	model = Usuario
	context_object_name = 'lista_de_profesores'
	def get_queryset(self):
		profesores = Usuario.objects.filter(profesorSinVerificar=True)
		return profesores

class VerificarProfesorA(RequiereLogin, EsAdmin, View):
	verificar = True;
	def get(self, request, *args, **kwargs):
		profid = self.kwargs['prof']
		prof = Usuario.objects.get(id=profid)
		if self.verificar:
			prof.profesorSinVerificar = False
			prof.is_staff = True
			prof.save()
		else:
			prof.delete()
		return redirect('/verificarprofesor/')

class ListaGestionCursos (RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/gestioncursos.html'
	model = Curso
	context_object_name = 'lista_de_cursos'
	def get_queryset(self):
		cursos = Curso.objects.all()
		return cursos

class ListaGestionAsignaturas (RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/gestionasignaturas.html'
	model = Asignatura
	context_object_name = 'lista_de_asignaturas'
	def get_queryset(self):
		asignaturas = Asignatura.objects.all()
		return asignaturas

class ListaGestionCarreras (RequiereLogin, EsAdmin, ListView):
	template_name = 'gestion/gestioncarreras.html'
	model = Carrera
	context_object_name = 'lista_de_carreras'
	def get_queryset(self):
		carreras = Carrera.objects.all()
		return carreras

class NuevoCurso (RequiereLogin, EsAdmin, FormView):
	template_name = 'gestion/nuevo.html'
	form_class = CursoForm
	success_url = '/gestioncursos/'
	def form_valid(self, form):
		form.save()
		return super(NuevoCurso, self).form_valid(form)

class NuevaAsignatura (RequiereLogin, EsAdmin, FormView):
	template_name = 'gestion/nuevo.html'
	form_class = AsignaturaForm
	success_url = '/gestionasignaturas/'
	def form_valid(self, form):
		form.save()
		return super(NuevaAsignatura, self).form_valid(form)

class NuevaCarrera (RequiereLogin, EsAdmin, FormView):
	template_name = 'gestion/nuevo.html'
	form_class = CarreraForm
	success_url = '/gestioncarreras/'
	def form_valid(self, form):
		form.save()
		return super(NuevaCarrera, self).form_valid(form)

class ListaAsigProf (RequiereLogin, EsProfesor, View):
	template_name = 'gestion/listaasignaturasprof.html'
	context_object_name = 'lista_de_asignaturas'
	calificar=False
	def get(self, request):
		carreras = request.user.imparte.all()
		return render(request, self.template_name, {self.context_object_name:carreras, 'calificar':self.calificar})

def cursoActual():
	if (date.today().month < settings.FIN_CURSO_MES):
		year=date.today().year-1
	elif (date.today().moth == settings.FIN_CURSO_MES and date.today().day < settings.FIN_CURSO_DIA):
		year=date.today().year-1
	else:
		year=date.today().year
	curso=Curso.objects.get(year=year)
	return curso;

class ListaAlum (RequiereLogin, EsProfesor, View):
	template_name = 'gestion/listaalumnosprof.html'
	context_object_name = 'lista_de_matriculas'
	actual = False
	def get(self, request, *args, **kwargs):
		if self.actual:
			curso = cursoActual()
		else:
			curso = Curso.objects.get(id=self.kwargs['curso'])
		matriculas = MatriculaAsignatura.objects.filter(curso=curso, asignatura=self.kwargs['asig'])
		context = {self.context_object_name:matriculas,}
		if self.actual: context['calificar']=True
		return render(request, self.template_name, context)

class ListaCursosProf (RequiereLogin, EsProfesor, View):
	template_name = 'gestion/listacursosprof.html'
	context_object_name = 'lista_de_cursos'
	def get(self, request, *args, **kwargs):
		cursos = Curso.objects.filter(year__lte=cursoActual().year)
		return render(request, self.template_name, {self.context_object_name:cursos,})

class Calificar(RequiereLogin, EsProfesor, View):
	template_name = 'gestion/calificar.html'
	form_class = CalificarForm
	def get(self, request, *args, **kwargs):
		matricula=MatriculaAsignatura.objects.get(curso=cursoActual(), alumno=self.kwargs['alum'], asignatura=self.kwargs['asig'])
		form = self.form_class(instance=matricula)
		context = {'form':form, 'matricula':matricula}
		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		matricula=MatriculaAsignatura.objects.get(curso=cursoActual(), alumno=self.kwargs['alum'], asignatura=self.kwargs['asig'])
		if form.is_valid():
			matriculaf = form.save(commit=False)
			matricula.nota1=matriculaf.nota1
			matricula.nota2=matriculaf.nota2
			matricula.matriculaHonor1=matriculaf.matriculaHonor1
			matricula.matriculaHonor2=matriculaf.matriculaHonor2
			matricula.noPresentado1=matriculaf.noPresentado1
			matricula.noPresentado2=matriculaf.noPresentado2
			matricula.save()
			return redirect('/calificar/'+self.kwargs['asig'])
		else:
			context = {'form':form, 'matricula':matricula}

gestion/templates/gestion/calificar.html
{% extends 'base.html' %}
{% block calificara %}active{% endblock %}
{% block titulo %}Calificar Alumnos{% endblock %}
{% block content %}
<div style="width:80%; margin:auto;">
	<p><strong>Alumno:</strong> {{ matricula.alumno.first_name }} {{ matricula.alumno.last_name }}</p>
	<p><strong>Asignatura:</strong> {{ matricula.asignatura.nombre }}</p>
	<p><strong>Curso:</strong> {{ matricula.curso.getCadena }}</p>
	<form method="post">
		{% csrf_token %}
		<table>
		<tr><td width="200px"></td></tr>
		{{ form }}
		</table><br>
		<input type="submit" value="Guardar" class="btn btn-default"/>
	</form>
</div>
{% endblock %}

gestion/templates/gestion/gestionasignaturas.html
{% extends "base.html" %}
{% block asignaturasa %}active{% endblock %}
{% block titulo %}Lista de Asignaturas{% endblock %}
{% block content %}
{% if lista_de_asignaturas %}
	<p><table class="table table-striped">
	<tr><th>Nombre</th><th>Carrera</th><th>Curso</th><th>Cuatrimestre</th></tr>
	{% for asig in lista_de_asignaturas %}
		<tr><td>{{ asig.nombre }}</td><td>{{ asig.carrera.nombre }}</td><td>{{ asig.curso }}</td><td>{{ asig.cuatrimestre }}</td></tr>
	{% endfor %}
	</table></p>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay ninguna asignatura disponible.
    </div>
{% endif %}
<p><a class="btn btn-primary" href="{% url 'gestion:nuevaasignatura' %}">Nueva Asignatura</a></p>
{% endblock %}

gestion/templates/gestion/gestioncursos.html
{% extends "base.html" %}
{% block cursosa %}active{% endblock %}
{% block titulo %}Lista de Cursos{% endblock %}
{% block content %}
<div style="width:50%; margin:auto;">
{% if lista_de_cursos %}
	<ul class="list-group">
	{% for curso in lista_de_cursos %}
		<li class="list-group-item"><h4 align=center>{{ curso.getCadena }}</h4></li>
	{% endfor %}
	</ul>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay ningún curso disponible.
    </div>
{% endif %}
<br><p><a class="btn btn-primary" href="{% url 'gestion:nuevocurso' %}">Nuevo Curso</a></p>
</div>
{% endblock %}

gestion/templates/gestion/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block indexa %}active{% endblock %}
{% block titulo %}Gestión de Matrícula{% endblock %}
{% block content %}
<table align=center width=70%><tr><td width=30%><img src="{% static 'gestion/matricula.png' %}" alt="Matrícula"/></td><td><h4 class="text-justify">Este sitio web está dedicado a la gestión de matrículas de una universidad. Los alumnos podrán matricularse en las asignaturas que deseen para un determinado curso siempre que el plazo de matrícula esté abierto así como consultar los resultados de su expediente académico. Los profesores podrán calificar las distintas convocatorias de sus alumnos.</h4></td></tr></table>
{% endblock %}

gestion/templates/gestion/listaalumnosprof.html
{% extends "base.html" %}

{% block calificara %}{% if calificar %}active{% endif %}{% endblock %}
{% block todosa %}{% if not calificar %}active{% endif %}{% endblock %}

{% block titulo %}
{% if calificar %}
	Calificar Alumnos
{% else %}
	Consultar Todos los Cursos
{% endif %}
{% endblock %}

{% block content %}

{% if lista_de_matriculas %}
	<table class="table">
	<tr><th>Nombre</th><th>Primera Convocatoria</th><th>Segunda Convocatoria</th><th></th></tr>
	{% for mat in lista_de_matriculas %}
		<tr><td>{{ mat.alumno.first_name }} {{ mat.alumno.last_name }}</td>
		<td>{% if mat.noPresentado1 %}NP{% elif mat.nota1 == NULL %}NE{% else %}<p class="{% if mat.nota1 >= 5 %}text-success{% else %}text-danger{% endif %}">{{ mat.nota1 }}{% if mat.matriculaHonor1 %} (MH){% endif %}{% endif %}</p></td>
		<td>{% if mat.noPresentado2 %}NP{% elif mat.nota2 == NULL %}NE{% else %}<p class="{% if mat.nota2 >= 5 %}text-success{% else %}text-danger{% endif %}">{{ mat.nota2 }}{% if mat.matriculaHonor2 %} (MH){% endif %}{% endif %}</p></td>
		<td><a href="{% url 'gestion:consultar' mat.asignatura.id mat.curso.id mat.alumno.id %}" class="btn btn-default">Detalles</a>{% if calificar %} <a class="btn btn-success" href="{{ request.path }}{{ mat.alumno.id }}">Calificar</a>{% endif %}</td>
		</tr>
	{% endfor %}
	</table>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay ningún alumno matriculado este curso.
    </div>
{% endif %}
{% endblock %}

gestion/templates/gestion/listaasignaturas.html
{% extends "base.html" %}

{% block calificara %}active{% endblock %}

{% block titulo %}Consulta del Expediente{% endblock %}

{% block content %}
{% if lista_de_matriculas %}
	<table class="table">
	<tr><th>Nombre</th><th>Cuatrimestre</th><th>Primera Convocatoria</th><th>Segunda Convocatoria</th><th></th></tr>
	{% for mat in lista_de_matriculas %}
		<tr><td>{{ mat.asignatura.nombre }}</td><td>{{ mat.asignatura.cuatrimestre }}</td>
		<td>{% if mat.noPresentado1 %}NP{% elif mat.nota1 == NULL %}NE{% else %}<p class="{% if mat.nota1 >= 5 %}text-success{% else %}text-danger{% endif %}">{{ mat.nota1 }}{% if mat.matriculaHonor1 %} (MH){% endif %}{% endif %}</p></td>
		<td>{% if mat.noPresentado2 %}NP{% elif mat.nota2 == NULL %}NE{% else %}<p class="{% if mat.nota2 >= 5 %}text-success{% else %}text-danger{% endif %}">{{ mat.nota2 }}{% if mat.matriculaHonor2 %} (MH){% endif %}{% endif %}</p></td>
		<td><a href="{{ request.path }}{{ mat.asignatura.id }}" class="btn btn-default">Detalles</a></td>
		</tr>
	{% endfor %}
	</table>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay asignaturas disponibles.
    </div>
{% endif %}
{% endblock %}

gestion/templates/gestion/listacursosexp.html
{% extends "base.html" %}
{% block expedientea %}active{% endblock %}
{% block titulo %}Consulta del Expediente{% endblock %}
{% block content %}
{% if lista_de_cursos %}
	<div class="list-group" style="margin:auto; width:60%">
	{% for curso in lista_de_cursos %}
		<a class="list-group-item" href="{% url 'gestion:curso' curso.id %}"><h4 align=center>{{ curso.getCadena }}</h4></a>
	{% endfor %}
	</div>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No estás matriculado en ningún curso.
    </div>
{% endif %}
{% endblock %}

gestion/templates/gestion/listacursosmat.html
{% extends "base.html" %}
{% block titulo %}Nueva Matrícula{% endblock %}
{% block matricularmea %}active{% endblock %}
{% block content %}
{% if lista_de_cursos %}
	 <div class="list-group" style="margin:auto; width:60%">
	 {% for curso in lista_de_cursos %}
  	  <a href="{% url 'gestion:matricula' curso.id %}" class="list-group-item{% if not curso.abierto %} disabled{% endif %}"><h4 align=center><strong>{{ curso.getCadena }}</strong> - <b class="text-{% if curso.abierto %}success{% else %}danger{% endif %}">Plazo de matrícula 
		{% if curso.abierto %}
			abierto
		{% else %}
			cerrado
		{% endif %}</b>
		 ({{ curso.inicioMatricula }} - {{ curso.finMatricula }})</h4></a>
      {% endfor %}
	 </div>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay ningún curso disponible.
    </div>
{% endif %}
{% endblock %}

gestion/templates/gestion/listacursosprof.html
{% extends "base.html" %}
{% block todosa %}active{% endblock %}
{% block titulo %}Consultar Todos los Cursos{% endblock %}
{% block content %}
{% if lista_de_cursos %}
	<div class="list-group" style="width:50%; margin:auto;">
	{% for curso in lista_de_cursos %}
		<a href="{{ request.path }}{{ curso.id }}" class="list-group-item"><h4 align=center>{{ curso.getCadena }}</h4></a>
	{% endfor %}
	</div>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay cursos disponibles.
    </div>
{% endif %}
{% endblock %}

gestion/templates/gestion/nuevo.html
{% extends 'base.html' %}
{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.min.js"></script>
<script>
	$( document ).ready(function() {
		$('#id_inicioMatricula').datepicker();
		$('#id_finMatricula').datepicker();
	});
</script>
{% endblock %}
{% block titulo %}Nuevo{% endblock %}
{% block content %}
	<div style="width:80%; margin:auto;">
	<form method="post" action="">
	    {% csrf_token %}
	    <table>
	    <tr><td width=150px></td></tr>
	    {{ form }}
	    </table>
	    <br><br><input type="submit" value="Guardar" class="btn btn-default"/>
	</form>
	</div>
{% endblock %}

gestion/templates/gestion/verificarprofesor.html
{% extends "base.html" %}
{% block verificara %}active{% endblock %}
{% block titulo %}Verificar Profesores{% endblock %}
{% block content %}
{% if lista_de_profesores %}
	<table class="table" width=100%>
		<tr><th>Usuario</th><th>Email</th><th>Nombre</th><th>Acciones</th></tr>
	{% for prof in lista_de_profesores %}
		<tr><td>{{ prof.username }}</td><td>{{ prof.email }}</td><td>{{ prof.first_name }} {{ prof.last_name }}</td><td><a href="{% url 'gestion:verificarp' prof.id %}" class="btn btn-success">Verificar</a> <a class="btn btn-danger" href="{% url 'gestion:eliminarp' prof.id %}">Eliminar</a></td></tr>
	{% endfor %}
	</table>
{% else %}
	<div class="alert alert-danger">
      <strong>Error!</strong> No hay ningún profesor sin verificar.
    </div>
{% endif %}
{% endblock %}